name: Create Draft Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-release:
    # PRがマージされた場合、かつ「bump-version/」から始まるブランチだった場合のみ実行
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'bump-version/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          VERSION=${BRANCH_NAME#bump-version/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get filename
        id: get_file_name
        run: |
          # config.json から最新の本体ファイル名を取得
          FILENAME=$(jq -r '.excel_file' config.json)
          echo "FILE_NAME=$FILENAME" >> $GITHUB_ENV

      - name: Generate Manual Release Notes Template
        id: manual_notes
        run: |
          # ヒアドキュメントを使ってMarkdownファイルを生成
          # バッククリック（`）はシェルスクリプト内でエスケープしています
          # EOFの競合や改行を安全に扱うため、ファイル経由で格納します
          cat << EOF > release_note_template.md

          <!--
          リリース後のTODO
          - 現行のバージョンでアップデート案内が出ること＆案内先でダウンロードできることを確認
          -->

          ## 💡 **ご利用になる方へ**
          本ツールを実行するには、下部にある **「Assets」** セクションから **\`${{ env.FILE_NAME }}\`** をダウンロードしてください。
          （\`Source code\` と書かれたZipファイルは通常ダウンロード不要です）


          ## 変更内容

          ### ✨ 新機能１
          - 簡単な説明文 or 機能詳細１
          - 簡単な説明文 or 機能詳細２
          - 簡単な説明文 or 機能詳細３

          ### 🐛 バグ修正１
          - 簡単な説明文 or バグ詳細１
          - 簡単な説明文 or バグ詳細２
          - 簡単な説明文 or バグ詳細３

          ### その他の変更
          - 変更詳細１
          - 変更詳細２
          - 変更詳細３


          ## ❌ 「マクロの実行がブロックされました」の対処方法

          1. ファイルを右クリック ＞ **プロパティ** を開き、最下部の **「ブロック解除」** にチェックを入れて [OK] を押します（Windowsのセキュリティ対策）。
          2. Excelでファイルを開き、「マクロを有効にする」を選択してご利用ください。
          EOF

      - name: Create Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
          body_path: release_note_template.md  # 生成したテンプレートファイルを指定
          draft: true
          # 上のステップで確認が取れたファイル名を動的に指定
          files: ${{ env.FILE_NAME }}
